<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SteelConveyorWar.Core\SteelConveyorWar.Core.csproj" />
  </ItemGroup>

</Project>
