<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SteelConveyorWar.Core\SteelConveyorWar.Core.csproj" />
    <ProjectReference Include="..\SteelConveyorWar.Sfml\SteelConveyorWar.Sfml.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\config\*.json" Link="config\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\config\maps\**\*.json" Link="config\maps\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
